package local:flecs;

world flecs-world {
    export create-world: func() -> u64;
    export delete-world: func(world-handle: u64);
    export new-entity: func(world-handle: u64) -> u64;
    export add-component: func(world-handle: u64, entity: u64, component: u64);
}