package local:flecs;


interface flecs-world {
    ecs-init: func(world-handle: u64) -> u64;
    ecs-mini: func() -> u64;
    ecs-fini: func(world-handle: u64) -> s64;
    ecs-is-fini: func(world-handle: u64) -> bool;
}

interface flecs-entity {
    ecs-new: func(world-handle: u64) -> u64;
    ecs-new-low-id: func(world-handle: u64) -> u64;
}


world flecs {
    export flecs-world;
    export flecs-entity;
}