package component:flecs;

interface flecs-world {
    type ecs-id-t = u64;
    type ecs-entity-t = ecs-id-t;

    ecs-init: func() -> u64;
    ecs-mini: func() -> u64;
    ecs-fini: func(world-handle: u64) -> s64;
    ecs-is-fini: func(world-handle: u64) -> bool;
}

interface flecs-entity {
    type ecs-id-t = u64;
    type ecs-entity-t = ecs-id-t;

    ecs-new: func(world-handle: u64) -> u64;
    ecs-new-low-id: func(world-handle: u64) -> u64;
    ecs-add-id: func(world-handle: u64, entity: ecs-entity-t, component: ecs-id-t);
}


world flecs {
    export flecs-world;
    export flecs-entity;
}